# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f06c21075131b2a68d9d4897d5eadc632779eb564f8b6be5f6e71bdd5cee4f4409f7ef5e88bceb370f83a5b956d30dfec6f1fb81430f562e3686998ec6b997

test:
  secret_key_base: 2bef99915772b079a24c925dc5305d3698f739e6769fbee0425368f3b0252fd63bf3c7b2c91d828bbe92263c4d8339f0394aba56a09171fa737d11ea422e9727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
